[project]
name = "spotify-organizer"
version = "0.1.0"
description = "Organize your Spotify playlists with ease."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pydantic-settings>=2.14.1",
    "ruff>=0.15.12",
    "spotipy>=2.26.0",
    "ty>=0.0.34",
]

[build-system]
requires = ["hatchling >= 1.26", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"
fallback-version = "0.1.0"

[project.scripts]
spotify-organizer = "spotify_organizer.main:main"
